# Generated by Django 5.2.1 on 2026-06-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_type', models.CharField(choices=[('sleeve', 'Sleeve Cut'), ('neck', 'Neckline'), ('length', 'Hemline Length'), ('fabric', 'Fabric Material'), ('color', 'Color Shade')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('extra_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
