# Generated by Django 6.0.5 on 2026-06-04 23:32

from django.db import migrations
from django.conf import settings

def create_superuser_run(apps, schema_editor):
    pass


def reverse_superuser_run(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_ateliersetting'),
    ]

    operations = [
        migrations.RunPython(create_superuser_run, reverse_superuser_run),
    ]

